### ISSUE TITLE
ALL_min_profit does not work with SellStrat = GAIN?

### ISSUE THREAD

**Issue by TomBos** [stevenshizzleh/pt_disciplined_trading#4]
Hey Steven, I read in the wiki:

ALL_min_profit = 1
Valid Values: Decimal numbers greater than or equal to 0.
Use the value to ensure you have reached a suitable profit level when using HIGHBB as a sell strategy.
NOTE: Not used with GAIN strategy.

**Comment by stevenshizzleh** [comment]
Oh snap! Thanks much. I'll take this out and roll it into the next release :D
