### ISSUE TITLE
Problem with "Very Bearish" Market settings

### ISSUE THREAD

**Issue by JackONeill12** [stevenshizzleh/pt_disciplined_trading#5]
On your new settings if the Market turns Very bearish you deactivate DCA and decrease the sell value by 25%. But at the moment this only affects the DCA sell which doesn't make sense since all coins got moved out of DCA. In the Pairs tab, the sell value is still at 3%.

**Comment by TomBos** [comment]
Made more sense if -25 % was moved to PAIRS, right?

(which I just did) ;-)

**Comment by JackONeill12** [comment]
Exactly.

**Comment by stevenshizzleh** [comment]
Good catch. Fixing right now, thanks!
