### ISSUE TITLE
Source Code.zip contains only the Readme.md?

### ISSUE THREAD

**Issue by TomBos** [stevenshizzleh/pt_disciplined_trading#6]
Hey Steven, love the work and research you're doing.

But! When I want to download eeeeverything, I was hoping everything was packed in the "Source Code.zip" - file, but only the Readme.md is in this zip-file.

Is it possible to include all the setting files in one zip?

(I'm no GitHib hero, so it could be my mistake, btw!)

**Comment by stevenshizzleh** [comment]
I'm not the best at using GitHub. Still learning. Think I got this figured out though! Thanks for opening the issue!

**Comment by TomBos** [comment]
Steven, thumbs up for the quick reaction!
